server:
  port: 8333

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:mem:prod_db
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate.ddl-auto: none
    #show-sql: true
    #properties.hibernate.format_sql: true

swagger:
  title: Purser
  version: 1.0